Name:           ros-hydro-pr2-simple-interface
Version:        1.0.5
Release:        0%{?dist}
Summary:        ROS pr2_simple_interface package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/pr2_simple_interface
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-actionlib
Requires:       ros-hydro-face-detector
Requires:       ros-hydro-pr2-gripper-sensor-action
Requires:       ros-hydro-pr2-gripper-sensor-controller
Requires:       ros-hydro-pr2-gripper-sensor-msgs
Requires:       ros-hydro-roscpp
Requires:       ros-hydro-rospy
Requires:       ros-hydro-sound-play
BuildRequires:  ros-hydro-actionlib
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-face-detector
BuildRequires:  ros-hydro-pr2-gripper-sensor-action
BuildRequires:  ros-hydro-pr2-gripper-sensor-controller
BuildRequires:  ros-hydro-pr2-gripper-sensor-msgs
BuildRequires:  ros-hydro-roscpp
BuildRequires:  ros-hydro-rospy
BuildRequires:  ros-hydro-sound-play

%description
pr2_simple_interface

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Wed Sep 17 2014 Austin Hendrix <ahendrix@willowgarage.com> - 1.0.5-0
- Autogenerated by Bloom

* Wed Sep 10 2014 Austin Hendrix <ahendrix@willowgarage.com> - 1.0.3-0
- Autogenerated by Bloom

